### PR TITLE
Fix/10 app undefined

### PR DESCRIPTION
**Pull request by lewisdaly**
Fix the os x startup crash, where app is undefined.

### CODE REVIEW

**Comment by davila9210** [comment]
Can confirm this solved booting. However the app still doesn't work on my os x (login button not responding)

**Review by xx10t4 — APPROVED** [review]
Thanks for fixing this. As I have indicated in other places I do not currently have access to a Mac so cannot test any OSX specific functionality, but this does look like it should fix the issue. For posterity I will note that the 0.0.6 OSX binaries have a fix similar to this that has not been pushed to github. I will discard that fix in favor of this one since they ultimately have the same effect.

**Comment by xx10t4** [comment]
@davila9210 Are you getting the error described in https://github.com/xx10t4/iota1k/issues/10 ? You should be able to see any errors in View -> Developer Tools. If your error is different than  https://github.com/xx10t4/iota1k/issues/10, please open a new issue.

**Comment by xx10t4** [comment]
@lewisdaly I am assuming you are on  OSX. Are you able to run the app under NPM or Yarn? It seem the 0.0.6 binary for OSX that I created on Ubuntu do not work, so I am trying to determine if it is a compile issue or something more fundamental.

**Comment by lewisdaly** [comment]
@xx10t4 I'm using yarn, on macOS ElCapitan - 10.11.6 (this is not the latest btw)
```
> yarn --version
0.27.5
> node --version
v6.5.0
> npm --version
5.3.0
```

I've managed to get it working with both npm and yarn. I can take a look at the maxOS (OS X) binary today if I get the chance.

**Pull request merged**
